ALTER SESSION SET "_ORACLE_SCRIPT" = true;

CREATE USER teste2 IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE TO teste2;
ALTER USER teste2 QUOTA UNLIMITED ON USERS;

-- Permissões
GRANT SELECT ON SYS.seq_test TO teste2;
GRANT SELECT ON SYS.seq_test_2 TO teste2;

GRANT SELECT, INSERT ON SYS.tabela_sequencias TO teste2;
GRANT CREATE SYNONYM TO teste2;